[project]
name = "WanX-EI-Studio"
version = "0.1.0"
description = ""
readme = "README.md"
authors = [
    { name = "Xiang Yang", email = "ryu-yang@qq.com" }
]
requires-python = ">=3.8,<4.0"
dependencies = [
    "gevent>=24.0.0,<26.0.0",
    "flask-cors>=5.0.0,<7.0.0",
    "pyzmq>=27.0.0,<28.0.0",
    "pynput>=1.8.1,<2.0.0",
    "python-socketio>=5.13.0,<6.0.0",
    "websocket-client>=1.8.0,<2.0.0",
    "schedule>=1.2.2,<2.0.0",
    "pillow>=10.4.0,<12.0.0",
    "datasets>=3.1.0,<4.0.0",
    "jsonlines>=4.0.0,<5.0.0",
    "huggingface-hub>=0.33.0,<0.34.0",
    "gymnasium>=1.1.1,<2.0.0",
    "einops>=0.8.1,<0.9.0",
    "safetensors>=0.5.3,<0.6.0",

    "diffusers>=0.33.1,<0.34.0",
    "pymunk>=6.11.1,<8.0.0",

    "imagecodecs>=2023.3.16,<2026.0.0",
    "tensorflow-datasets>=4.9.2,<5.0.0",
    "draccus>=0.9.3,<0.12.0",
    "flask==3.0.3",
    "deepdiff>=8.4.2,<9.0.0",
    "zarr>=2.16.1,<4.0.0",
    "numba>=0.58.1,<0.62.0",
    "flask-socketio>=5.5.1,<6.0.0",
    "matplotlib>=3.7.5",
    "sounddevice",
    "soundfile",
    "seaborn",
    "rerun-sdk (==0.22.0)",
    "robotic-arm (>=1.0.6,<2.0.0)",
    "websockets",
    "protobuf==4.21",
    "colorama",
    "scipy",
    "logging_mp"
]

[tool.setuptools.packages.find]
where = ["."]
include = ["operating_platform*"]
exclude = ["operating_platform.server*"]

[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"
