[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "robodriver-teleoperator-autotask"
version = "0.0.1"
readme = "README.md"
requires-python = ">=3.8"
license = {text = "Apache License 2.0"}
authors = [
    {name = "Xiang Yang", email = "yangxiang@baai.ac.cn"},
]
keywords = ["robotics", "lerobot", "so101"]
dependencies = [
    "logging_mp"
]

[tool.setuptools.packages.find]
include = [
    "robodriver_teleoperator_autotask",
    "lerobot_teleoperator_autotask",
]
